name: Generate profile metrics

on:
  schedule:
    - cron: "0 */12 * * *"   # every 12 hours
  workflow_dispatch:

permissions:
  contents: write   # needed to push the generated SVGs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # --- (A) One big, everything-but-the-kitchen-sink SVG ---
      - name: Build main metrics (classic template)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.USER_TOKEN }}
          user: zcourts
          template: classic
          config_timezone: Europe/Warsaw
          config_animations: yes
          config_output: metrics.svg
          base: header, activity, community, repositories, metadata

          # Core GitHub stats
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_details: bytes-size, percentage
          plugin_languages_ignored: html, css
          plugin_languages_limit: 12
          plugin_languages_sections: most-used, recently-used
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_trim: yes
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: X # bronze/silver/gold; X shows all
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_stargazers: yes
          plugin_stargazers_charts: yes
          plugin_starlists: yes
          plugin_starlists_limit_repositories: 4
          plugin_lines: yes
          plugin_repositories: yes
          plugin_repositories_featured: zcourts/REPO1, zcourts/REPO2
          plugin_people: yes
          plugin_people_types: followers, following
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_repositories: yes
          plugin_topics: yes
          plugin_topics_limit: 12
          plugin_projects: yes
          plugin_projects_limit: 4
          plugin_discussions: yes
          plugin_gists: yes
          plugin_reactions: yes
          plugin_licenses: yes
          plugin_traffic: yes

          # Fun/extra (toggle as you like)
          plugin_code: yes
          plugin_code_load: 400
          plugin_skyline: yes
          plugin_skyline_year: current-year
          plugin_support: no    # deprecated upstream; leave off

      # --- (B) Focused: Languages deep-dive ---
      - name: Build languages deep-dive
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.USER_TOKEN }}
          user: zcourts
          template: classic
          config_output: metrics.languages.svg
          base: repositories
          plugin_languages: yes
          plugin_languages_indepth: yes      # clones & analyzes (slower)
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_load: 500
          plugin_languages_recent_days: 14
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_limit: 16
          plugin_languages_threshold: 0%

      # --- (C) Focused: Activity habits ---
      - name: Build activity habits
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.USER_TOKEN }}
          user: zcourts
          template: classic
          config_output: metrics.habits.svg
          base: ""
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_facts: yes
          plugin_habits_trim: yes

      # --- (D) Focused: Achievements ---
      - name: Build achievements
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.USER_TOKEN }}
          user: zcourts
          template: classic
          config_output: metrics.achievements.svg
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: X

      # --- (E) Focused: Follow-up (issues/PRs) ---
      - name: Build follow-up
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.USER_TOKEN }}
          user: zcourts
          template: classic
          config_output: metrics.followup.svg
          base: ""
          plugin_followup: yes
          plugin_followup_sections: repositories, user

      # --- (F) Focused: Stargazers timelines ---
      - name: Build stargazers
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.USER_TOKEN }}
          user: zcourts
          template: classic
          config_output: metrics.stargazers.svg
          base: ""
          plugin_stargazers: yes
          plugin_stargazers_charts: yes

      # --- (G) Optional social/dev extras ---
      # WakaTime
      - name: Build WakaTime (optional)
        if: ${{ secrets.WAKATIME_API_KEY != '' }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.USER_TOKEN }}
          user: zcourts
          template: classic
          config_output: metrics.wakatime.svg
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_days: 7
          plugin_wakatime_sections: time, projects, projects-graphs, languages, editors, os

      # Stack Overflow
      - name: Build StackOverflow (optional)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.USER_TOKEN }}
          user: zcourts
          template: classic
          config_output: metrics.stackoverflow.svg
          base: ""
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 0000000  # <-- your numeric SO user id
          plugin_stackoverflow_sections: answers-top, answers-recent

      # Last.fm “recently listened”
      - name: Build Music (optional)
        if: ${{ secrets.LASTFM_API_KEY != '' && secrets.LASTFM_USER != '' }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.USER_TOKEN }}
          user: zcourts
          template: classic
          config_output: metrics.music.svg
          base: ""
          plugin_music: yes
          plugin_music_provider: lastfm
          plugin_music_token: ${{ secrets.LASTFM_API_KEY }}
          plugin_music_user: ${{ secrets.LASTFM_USER }}
          plugin_music_mode: recent

      # PageSpeed for your site
      - name: Build PageSpeed (optional)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.USER_TOKEN }}
          user: zcourts
          template: classic
          config_output: metrics.pagespeed.svg
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_url: https://yourdomain.example

      # Commit any new/changed SVGs
      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add *.svg
          git commit -m "Update metrics" || echo "No changes"
          git push
